== DialogFlow Demo

=== Grails DialogFlow Plugin

Does two things:

* Uses data services, which calls a working DialogFlow skill with a query and returns results
* Uses webhook fulfillment - can fulfill an intent, slot, or domain

=== Data Services with Grails

You can call a working action on DialogFlow with a query and return a result.

Steps to build:

* Add plugin to build.gradle
* Add property 'apiAiKey' for your project to application.groovy or application.yml
* Create a controller that implements the trait AiServiceController

=== Data Services with Grails

* In the index action, implement the 3 lines from the example controller 'AiDataController'
* Do something with the response like converse with a query - you can proxy the interaction if you wish

=== Webhooks with Grails

DialogFlow allows you to build in GUI based project and interacts with itself, or call an outside service to fulfill and intent.

Steps to build:


* Add plugin to build.gradle
* Add property 'apiAiKey' for your project to application.groovy or application.yml
* Create a controller that implements the trait AiWebhookController
* Remove any index() action - the trait implements this for us
* Add a @Override method called doWebhook(AIWebhookServlet.AIWebhookRequest input, Fulfillment output)

=== Webhooks with Grails

* Create a project on DialogFlow
* Create an intent action with just about any parameter
* Click on fulfillment - enter the https url of your webhook controller index action
* Under domains select 'enable for all domains'
* Go back to DialogFlow console and activate intent via "Try it out"
* Demo - Yahoo Weather Webhook

